// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "app_blade/pkg/database"

const TableNameBladeUser = "blade_user"

// BladeUser 用户表
type BladeUser struct {
	ID       int64              `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                        // id
	Name     string             `gorm:"column:name;not null;comment:用户名" json:"name"`                                        // 用户名
	Password string             `gorm:"column:password;not null;comment:密码" json:"-"`                                        // 密码
	Age      int32              `gorm:"column:age;not null;comment:年龄" json:"age"`                                           // 年龄
	Email    string             `gorm:"column:email;not null;comment:邮箱" json:"email"`                                       // 邮箱
	Address  string             `gorm:"column:address;not null;comment:地址" json:"address"`                                   // 地址
	CreateAt database.LocalTime `gorm:"column:create_at;not null;default:1970-01-01 00:00:00;comment:创建时间" json:"create_at"` // 创建时间
	CreateBy string             `gorm:"column:create_by;not null;comment:创建人" json:"create_by"`                              // 创建人
	UpdateAt database.LocalTime `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"`   // 更新时间
	UpdateBy string             `gorm:"column:update_by;not null;comment:更新人" json:"update_by"`                              // 更新人
}

// TableName BladeUser's table name
func (*BladeUser) TableName() string {
	return TableNameBladeUser
}
