// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "app_blade/pkg/database"

const TableNameBladeProduct = "blade_product"

// BladeProduct mapped from table <blade_product>
type BladeProduct struct {
	ID          int64              `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                        // id
	Title       string             `gorm:"column:title;not null;comment:商品标题" json:"title"`                                     // 商品标题
	Price       float64            `gorm:"column:price;not null;default:0.00;comment:商品价格" json:"price"`                        // 商品价格
	Description string             `gorm:"column:description;not null;comment:商品描述" json:"description"`                         // 商品描述
	CreateAt    database.LocalTime `gorm:"column:create_at;not null;default:1970-01-01 00:00:00;comment:创建时间" json:"create_at"` // 创建时间
	CreateBy    string             `gorm:"column:create_by;not null;comment:创建人" json:"create_by"`                              // 创建人
	UpdateAt    database.LocalTime `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"`   // 更新时间
	UpdateBy    string             `gorm:"column:update_by;not null;comment:更新人" json:"update_by"`                              // 更新人
}

// TableName BladeProduct's table name
func (*BladeProduct) TableName() string {
	return TableNameBladeProduct
}
